CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price FLOAT,
    duration INTEGER
);

CREATE TABLE workdays (
    master_id BIGINT REFERENCES masters(id) ON DELETE CASCADE,
    day_of_work TIMESTAMP NOT NULL,
    shift_start TIME NOT NULL,
    shift_end TIME NOT NULL,
    break_start TIME,
    break_end TIME,
    PRIMARY KEY (master_id, day_of_work)
);