CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    number INT NOT NULL
);

CREATE TABLE procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price FLOAT,
    duration INTEGER
);

CREATE TABLE workdays (
    master_id BIGINT REFERENCES masters(id) ON DELETE CASCADE,
    day_of_work DATE NOT NULL,
    shift_start TIME NOT NULL,
    shift_end TIME NOT NULL,
    break_start TIME,
    break_end TIME,
    PRIMARY KEY (master_id, day_of_work)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id BIGINT REFERENCES masters(id) ON DELETE CASCADE,
    client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    procedure_id BIGINT REFERENCES procedures(id) ON DELETE CASCADE,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP
);